# Generated by Django 5.0.7 on 2024-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default='Yaroslav', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(default='Orlov', max_length=50, verbose_name='Last Name')),
                ('username', models.CharField(default='user', max_length=20, unique=True, verbose_name='username')),
                ('email', models.EmailField(default='email@example.com', max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Customs Users',
            },
        ),
    ]
